/** Public facade for the TypeScript project harness library API. */

export type {
  PackageJsonFacts,
  PackageJsonEntryFact,
  PackageJsonEntryTargetFact,
  PackageJsonScriptFact,
  PackageJsonWorkspaceFact,
  TypeScriptCompilerOptionFacts,
  RulePackDescriptor,
  SourceLocation,
  TypeScriptDiagnosticSeverity,
  TypeScriptExportFact,
  TypeScriptHarnessConfig,
  TypeScriptHarnessFinding,
  TypeScriptHarnessReport,
  TypeScriptHarnessRule,
  TypeScriptHarnessRunMode,
  TypeScriptImportFact,
  TypeScriptImportEdgeFact,
  TypeScriptModuleLayer,
  TypeScriptModuleReport,
  TypeScriptModuleRole,
  TypeScriptNativeDiagnostic,
  TypeScriptNativeDiagnosticRelatedInformation,
  TypeScriptNativeImportResolutionFact,
  TypeScriptPackageImportOwnerFact,
  TypeScriptPackageEntryResolutionFact,
  TypeScriptPathAliasFact,
  TypeScriptProjectHarnessAgentSnapshot,
  TypeScriptProjectHarnessAgentSnapshotPackage,
  TypeScriptProjectConfigFacts,
  TypeScriptProjectHarnessScope,
  TypeScriptProjectReferencePackageFact,
  TypeScriptProjectReferenceResolutionFact,
  TypeScriptReasoningDiagnosticFact,
  TypeScriptReasoningImportSummaryFact,
  TypeScriptReasoningModule,
  TypeScriptReasoningOwnerBranchFact,
  TypeScriptReasoningOwnerBranchRole,
  TypeScriptReasoningOwnerDependencyFact,
  TypeScriptReasoningSourceShadowFact,
  TypeScriptReasoningTree,
  TypeScriptWorkspacePackageFact,
} from "./model.js";
export {
  advisoryFindings,
  blockingFindings,
  fileCount,
  isTypeScriptHarnessClean,
  parsedCount,
} from "./model.js";
export {
  DEFAULT_IGNORED_DIR_NAMES,
  discoverTypeScriptFiles,
  parseTypeScriptProjectFiles,
  parseTypeScriptSourceFile,
  readProjectScope,
} from "./parser.js";
export {
  renderAssertionMessage,
  renderTypeScriptProjectHarness,
  renderTypeScriptProjectHarnessAgentSnapshot,
  renderTypeScriptProjectHarnessAdvice,
  renderTypeScriptProjectHarnessJson,
  renderTypeScriptReasoningTree,
} from "./render.js";
export type { TypeScriptRenderOptions } from "./render.js";
export {
  assertTypeScriptLangHarnessClean,
  assertTypeScriptProjectHarnessClean,
  buildTypeScriptProjectHarnessAgentSnapshot,
  defaultTypeScriptHarnessConfig,
  runTypeScriptLangHarness,
  runTypeScriptProjectHarnessAgentSnapshot,
  runTypeScriptProjectHarness,
} from "./runner.js";
export {
  typeScriptAgentPolicyRules,
  typeScriptModularityRules,
  typeScriptProjectPolicyRules,
  typeScriptRulePackDescriptors,
  typeScriptSemanticRules,
  typeScriptSyntaxRules,
  typeScriptTestLayoutRules,
} from "./rules.js";
