/**
 * Public facade for the ASP TypeScript library API.
 *
 * Exports are grouped by model, configuration, parsing, rendering, execution,
 * rules, and verification so consumers can select a stable responsibility
 * surface without reaching into implementation modules.
 */

export type {
  PackageJsonFacts,
  PackageJsonEntryFact,
  PackageJsonEntryTargetFact,
  PackageJsonScriptFact,
  PackageJsonWorkspaceFact,
  TypeScriptCompilerOptionFacts,
  RulePackDescriptor,
  SourceLocation,
  TypeScriptDiagnosticSeverity,
  TypeScriptExportFact,
  AspTypeScriptConfig,
  AspTypeScriptFinding,
  AspTypeScriptReport,
  AspTypeScriptRule,
  AspTypeScriptRunMode,
  TypeScriptRulePack,
  TypeScriptImportFact,
  TypeScriptImportEdgeFact,
  TypeScriptModuleLayer,
  TypeScriptModuleReport,
  TypeScriptModuleResponsibilityFact,
  TypeScriptModuleResponsibilityKind,
  TypeScriptModuleRole,
  TypeScriptNativeDiagnostic,
  TypeScriptNativeDiagnosticRelatedInformation,
  TypeScriptNativeImportResolutionFact,
  TypeScriptPackageBuildToolConfigSource,
  TypeScriptPackageBuildToolDependencySource,
  TypeScriptPackageBuildToolFact,
  TypeScriptPackageBuildToolName,
  TypeScriptPackageBuildToolSignalFact,
  TypeScriptPackageBuildToolSignalKind,
  TypeScriptPackageDependencyFact,
  TypeScriptPackageDependencySource,
  TypeScriptPackageImportOwnerFact,
  TypeScriptPackageEntryResolutionFact,
  TypeScriptPackageExtensionActivation,
  TypeScriptPackageExtensionConfigSource,
  TypeScriptPackageExtensionDependencySource,
  TypeScriptPackageExtensionFact,
  TypeScriptPackageExtensionName,
  TypeScriptPathAliasFact,
  AspTypeScriptAgentSnapshot,
  AspTypeScriptAgentSnapshotPackage,
  TypeScriptProjectConfigFacts,
  AspTypeScriptProjectScope,
  TypeScriptProjectReferencePackageFact,
  TypeScriptProjectReferenceResolutionFact,
  TypeScriptEffectErrorChannelKind,
  TypeScriptEffectConcurrencySignalFact,
  TypeScriptEffectConcurrencySignalKind,
  TypeScriptEffectProductionBoundaryMissingCapability,
  TypeScriptEffectProductionBoundarySignalFact,
  TypeScriptEffectProductionBoundarySignalKind,
  TypeScriptEffectPromiseInteropRiskFact,
  TypeScriptEffectPromiseInteropRiskKind,
  TypeScriptEffectResourceScopeRiskFact,
  TypeScriptEffectRuntimeCallFact,
  TypeScriptEffectRuntimeCallKind,
  TypeScriptEffectSchemaBoundarySignalFact,
  TypeScriptEffectSchemaBoundarySignalKind,
  TypeScriptEffectServiceContainerKind,
  TypeScriptEffectServiceMethodFact,
  TypeScriptPublicAsyncEffectSurfaceFact,
  TypeScriptPublicDataFieldFact,
  TypeScriptPublicDiscriminatedUnionVariantFieldFact,
  TypeScriptPublicFunctionControlFlowFact,
  TypeScriptPublicFunctionParamFact,
  TypeScriptPublicReturnObjectShapeFact,
  TypeScriptReactHookCallSignalFact,
  TypeScriptReactHookCallViolationKind,
  TypeScriptReactRenderOwnerKind,
  TypeScriptReactRenderPuritySignalFact,
  TypeScriptReactRenderPuritySignalKind,
  TypeScriptReactStaticDefinitionSignalFact,
  TypeScriptReactStaticDefinitionSignalKind,
  TypeScriptPublicTypeAliasFact,
  TypeScriptPublicTupleApiSurfaceFact,
  TypeScriptReasoningDiagnosticFact,
  TypeScriptReasoningImportSummaryFact,
  TypeScriptReasoningModule,
  TypeScriptReasoningOwnerBranchFact,
  TypeScriptReasoningOwnerBranchRole,
  TypeScriptReasoningOwnerDependencyFact,
  TypeScriptReasoningSourceShadowFact,
  TypeScriptReasoningTree,
  TypeScriptWorkspacePackageFact,
} from "./model.js";
export {
  advisoryFindings,
  blockingFindings,
  fileCount,
  isAspTypeScriptClean,
  parsedCount,
} from "./model.js";
export {
  defaultAspTypeScriptConfig,
  defaultTypeScriptVerificationPolicy,
  withDisabledTypeScriptRule,
  withDisabledTypeScriptRulePack,
  withDisabledTypeScriptRules,
  withDisabledTypeScriptVerificationTaskKind,
  withDisabledTypeScriptVerificationTaskKinds,
  withTypeScriptBlockingSeverities,
  withTypeScriptRulePackSeverity,
  withTypeScriptRuleSeverity,
  withTypeScriptVerificationDependencySignal,
  withTypeScriptVerificationProfileHint,
  withTypeScriptVerificationReceipt,
  withTypeScriptVerificationResponsibilityTaskKinds,
  withTypeScriptVerificationSkillBinding,
  withTypeScriptVerificationSkillDescriptor,
  withTypeScriptVerificationTaskContract,
  withTypeScriptVerificationWaiver,
} from "./config.js";
export {
  DEFAULT_IGNORED_DIR_NAMES,
  discoverTypeScriptFiles,
  parseTypeScriptProjectFiles,
  parseTypeScriptSourceFile,
  readProjectResolution,
} from "./parser.js";
export {
  renderAssertionMessage,
  renderAspTypeScript,
  renderAspTypeScriptAgentCompactText,
  renderAspTypeScriptAgentSnapshot,
  renderAspTypeScriptAdvice,
  renderAspTypeScriptJson,
  renderTypeScriptReasoningTree,
} from "./render.js";
export type {
  TypeScriptAgentCompactTextFindingMode,
  TypeScriptAgentCompactTextOptions,
  TypeScriptRenderOptions,
} from "./render.js";
export {
  assertAspTypeScriptAgentClean,
  assertAspTypeScriptEmbeddedClean,
  assertAspTypeScriptPathsClean,
  assertAspTypeScriptClean,
  buildAspTypeScriptAgentSnapshot,
  runAspTypeScriptPaths,
  runAspTypeScriptAgentSnapshot,
  runAspTypeScript,
} from "./runner.js";
export type { AspTypeScriptEmbeddedOptions } from "./runner.js";
export {
  typeScriptAgentPolicyRules,
  typeScriptExtensionPolicyRules,
  typeScriptModularityRules,
  typeScriptProjectPolicyRules,
  typeScriptRulePackDescriptors,
  typeScriptRulePackRuleIds,
  typeScriptSemanticRules,
  typeScriptSyntaxRules,
  typeScriptTestLayoutRules,
} from "./rules.js";
export {
  renderAspTypeScriptRulesMarkdown,
  aspTypeScriptRulesMarkdown,
  writeAspTypeScriptRulesToUnitTests,
} from "./rules/asp-rules.js";
export {
  activeTypeScriptVerificationProfileCandidates,
  activeTypeScriptVerificationProfileHints,
  buildTypeScriptVerificationPerformanceIndex,
  buildTypeScriptVerificationReportBundle,
  buildTypeScriptVerificationReportBundleWithOptions,
  buildTypeScriptVerificationProfileIndex,
  buildTypeScriptVerificationProfileIndexForReport,
  buildTypeScriptVerificationProfileIndexWithConfig,
  buildTypeScriptVerificationTaskIndex,
  defaultTypeScriptVerificationReportOptions,
  planTypeScriptProjectVerification,
  planTypeScriptProjectVerificationForReport,
  planTypeScriptProjectVerificationWithConfig,
  renderTypeScriptVerificationPlan,
  renderTypeScriptVerificationPerformanceIndex,
  renderTypeScriptVerificationPerformanceIndexJson,
  renderTypeScriptVerificationProfileIndex,
  renderTypeScriptVerificationProfileIndexJson,
  renderTypeScriptVerificationPlanJson,
  renderTypeScriptVerificationReportArtifactJson,
  renderTypeScriptVerificationReportBundleJson,
  renderTypeScriptVerificationSkillContracts,
  renderTypeScriptVerificationTaskIndexJson,
  TypeScriptVerificationReportWriteError,
  typeScriptVerificationProfileIndexIsClear,
  writeTypeScriptVerificationReports,
} from "./verification.js";
export type {
  TypeScriptOwnerResponsibility,
  TypeScriptVerificationDependencySignal,
  TypeScriptVerificationEvidence,
  TypeScriptVerificationPerformanceIndex,
  TypeScriptVerificationPerformanceRecord,
  TypeScriptVerificationPhase,
  TypeScriptVerificationPlan,
  TypeScriptVerificationPolicy,
  TypeScriptVerificationProfileCandidate,
  TypeScriptVerificationProfileCandidateState,
  TypeScriptVerificationProfileHint,
  TypeScriptVerificationProfileIndex,
  TypeScriptVerificationReceipt,
  TypeScriptVerificationReceiptStatus,
  TypeScriptVerificationReportArtifact,
  TypeScriptVerificationReportBundle,
  TypeScriptVerificationReportObligation,
  TypeScriptVerificationReportOptions,
  TypeScriptVerificationReportPersistence,
  TypeScriptVerificationReportTemplate,
  TypeScriptVerificationReportTraceConfig,
  TypeScriptVerificationReportWriteConfig,
  TypeScriptVerificationReportWriteReceipt,
  TypeScriptVerificationRequirement,
  TypeScriptVerificationResolutionNote,
  TypeScriptVerificationSkillBinding,
  TypeScriptVerificationSkillDescriptor,
  TypeScriptVerificationTask,
  TypeScriptVerificationTaskContract,
  TypeScriptVerificationTaskIndex,
  TypeScriptVerificationTaskKind,
  TypeScriptVerificationTaskRecord,
  TypeScriptVerificationTaskState,
  TypeScriptVerificationWaiver,
} from "./verification.js";
