/** Public facade for the TypeScript project harness library API. */

export type {
  PackageJsonFacts,
  PackageJsonEntryFact,
  PackageJsonEntryTargetFact,
  PackageJsonScriptFact,
  PackageJsonWorkspaceFact,
  TypeScriptCompilerOptionFacts,
  RulePackDescriptor,
  SourceLocation,
  TypeScriptDiagnosticSeverity,
  TypeScriptExportFact,
  TypeScriptHarnessConfig,
  TypeScriptHarnessFinding,
  TypeScriptHarnessReport,
  TypeScriptHarnessRule,
  TypeScriptHarnessRunMode,
  TypeScriptRulePack,
  TypeScriptImportFact,
  TypeScriptImportEdgeFact,
  TypeScriptModuleLayer,
  TypeScriptModuleReport,
  TypeScriptModuleRole,
  TypeScriptNativeDiagnostic,
  TypeScriptNativeDiagnosticRelatedInformation,
  TypeScriptNativeImportResolutionFact,
  TypeScriptPackageBuildToolConfigSource,
  TypeScriptPackageBuildToolDependencySource,
  TypeScriptPackageBuildToolFact,
  TypeScriptPackageBuildToolName,
  TypeScriptPackageBuildToolSignalFact,
  TypeScriptPackageBuildToolSignalKind,
  TypeScriptPackageImportOwnerFact,
  TypeScriptPackageEntryResolutionFact,
  TypeScriptPackageExtensionActivation,
  TypeScriptPackageExtensionConfigSource,
  TypeScriptPackageExtensionDependencySource,
  TypeScriptPackageExtensionFact,
  TypeScriptPackageExtensionName,
  TypeScriptPathAliasFact,
  TypeScriptProjectHarnessAgentSnapshot,
  TypeScriptProjectHarnessAgentSnapshotPackage,
  TypeScriptProjectConfigFacts,
  TypeScriptProjectHarnessScope,
  TypeScriptProjectReferencePackageFact,
  TypeScriptProjectReferenceResolutionFact,
  TypeScriptEffectErrorChannelKind,
  TypeScriptEffectConcurrencySignalFact,
  TypeScriptEffectConcurrencySignalKind,
  TypeScriptEffectPromiseInteropRiskFact,
  TypeScriptEffectPromiseInteropRiskKind,
  TypeScriptEffectResourceScopeRiskFact,
  TypeScriptEffectRuntimeCallFact,
  TypeScriptEffectRuntimeCallKind,
  TypeScriptEffectSchemaBoundarySignalFact,
  TypeScriptEffectSchemaBoundarySignalKind,
  TypeScriptEffectServiceContainerKind,
  TypeScriptEffectServiceMethodFact,
  TypeScriptPublicAsyncEffectSurfaceFact,
  TypeScriptPublicDataFieldFact,
  TypeScriptPublicDiscriminatedUnionVariantFieldFact,
  TypeScriptPublicFunctionControlFlowFact,
  TypeScriptPublicFunctionParamFact,
  TypeScriptPublicTypeAliasFact,
  TypeScriptPublicTupleApiSurfaceFact,
  TypeScriptReasoningDiagnosticFact,
  TypeScriptReasoningImportSummaryFact,
  TypeScriptReasoningModule,
  TypeScriptReasoningOwnerBranchFact,
  TypeScriptReasoningOwnerBranchRole,
  TypeScriptReasoningOwnerDependencyFact,
  TypeScriptReasoningSourceShadowFact,
  TypeScriptReasoningTree,
  TypeScriptWorkspacePackageFact,
} from "./model.js";
export {
  advisoryFindings,
  blockingFindings,
  fileCount,
  isTypeScriptHarnessClean,
  parsedCount,
} from "./model.js";
export {
  defaultTypeScriptHarnessConfig,
  defaultTypeScriptVerificationPolicy,
  withDisabledTypeScriptRule,
  withDisabledTypeScriptRulePack,
  withDisabledTypeScriptRules,
  withDisabledTypeScriptVerificationTaskKind,
  withDisabledTypeScriptVerificationTaskKinds,
  withTypeScriptBlockingSeverities,
  withTypeScriptRulePackSeverity,
  withTypeScriptRuleSeverity,
  withTypeScriptVerificationDependencySignal,
  withTypeScriptVerificationProfileHint,
  withTypeScriptVerificationReceipt,
  withTypeScriptVerificationResponsibilityTaskKinds,
  withTypeScriptVerificationSkillBinding,
  withTypeScriptVerificationSkillDescriptor,
  withTypeScriptVerificationTaskContract,
  withTypeScriptVerificationWaiver,
} from "./config.js";
export {
  DEFAULT_IGNORED_DIR_NAMES,
  discoverTypeScriptFiles,
  parseTypeScriptProjectFiles,
  parseTypeScriptSourceFile,
  readProjectScope,
} from "./parser.js";
export {
  renderAssertionMessage,
  renderTypeScriptProjectHarness,
  renderTypeScriptProjectHarnessAgentCompactText,
  renderTypeScriptProjectHarnessAgentSnapshot,
  renderTypeScriptProjectHarnessAdvice,
  renderTypeScriptProjectHarnessJson,
  renderTypeScriptReasoningTree,
} from "./render.js";
export type {
  TypeScriptAgentCompactTextFindingMode,
  TypeScriptAgentCompactTextOptions,
  TypeScriptRenderOptions,
} from "./render.js";
export {
  assertTypeScriptProjectHarnessAgentClean,
  assertTypeScriptProjectHarnessEmbeddedClean,
  assertTypeScriptLangHarnessClean,
  assertTypeScriptProjectHarnessClean,
  buildTypeScriptProjectHarnessAgentSnapshot,
  runTypeScriptLangHarness,
  runTypeScriptProjectHarnessAgentSnapshot,
  runTypeScriptProjectHarness,
} from "./runner.js";
export type { TypeScriptProjectHarnessEmbeddedOptions } from "./runner.js";
export {
  typeScriptAgentPolicyRules,
  typeScriptExtensionPolicyRules,
  typeScriptModularityRules,
  typeScriptProjectPolicyRules,
  typeScriptRulePackDescriptors,
  typeScriptRulePackRuleIds,
  typeScriptSemanticRules,
  typeScriptSyntaxRules,
  typeScriptTestLayoutRules,
} from "./rules.js";
export {
  activeTypeScriptVerificationProfileCandidates,
  activeTypeScriptVerificationProfileHints,
  buildTypeScriptVerificationPerformanceIndex,
  buildTypeScriptVerificationReportBundle,
  buildTypeScriptVerificationReportBundleWithOptions,
  buildTypeScriptVerificationProfileIndex,
  buildTypeScriptVerificationProfileIndexForReport,
  buildTypeScriptVerificationProfileIndexWithConfig,
  buildTypeScriptVerificationTaskIndex,
  defaultTypeScriptVerificationReportOptions,
  planTypeScriptProjectVerification,
  planTypeScriptProjectVerificationForReport,
  planTypeScriptProjectVerificationWithConfig,
  renderTypeScriptVerificationPlan,
  renderTypeScriptVerificationPerformanceIndex,
  renderTypeScriptVerificationPerformanceIndexJson,
  renderTypeScriptVerificationProfileIndex,
  renderTypeScriptVerificationProfileIndexJson,
  renderTypeScriptVerificationPlanJson,
  renderTypeScriptVerificationReportArtifactJson,
  renderTypeScriptVerificationReportBundleJson,
  renderTypeScriptVerificationSkillContracts,
  renderTypeScriptVerificationTaskIndexJson,
  TypeScriptVerificationReportWriteError,
  typeScriptVerificationProfileIndexIsClear,
  writeTypeScriptVerificationReports,
} from "./verification.js";
export type {
  TypeScriptOwnerResponsibility,
  TypeScriptVerificationDependencySignal,
  TypeScriptVerificationEvidence,
  TypeScriptVerificationPerformanceIndex,
  TypeScriptVerificationPerformanceRecord,
  TypeScriptVerificationPhase,
  TypeScriptVerificationPlan,
  TypeScriptVerificationPolicy,
  TypeScriptVerificationProfileCandidate,
  TypeScriptVerificationProfileCandidateState,
  TypeScriptVerificationProfileHint,
  TypeScriptVerificationProfileIndex,
  TypeScriptVerificationReceipt,
  TypeScriptVerificationReceiptStatus,
  TypeScriptVerificationReportArtifact,
  TypeScriptVerificationReportBundle,
  TypeScriptVerificationReportObligation,
  TypeScriptVerificationReportOptions,
  TypeScriptVerificationReportPersistence,
  TypeScriptVerificationReportTemplate,
  TypeScriptVerificationReportTraceConfig,
  TypeScriptVerificationReportWriteConfig,
  TypeScriptVerificationReportWriteReceipt,
  TypeScriptVerificationRequirement,
  TypeScriptVerificationResolutionNote,
  TypeScriptVerificationSkillBinding,
  TypeScriptVerificationSkillDescriptor,
  TypeScriptVerificationTask,
  TypeScriptVerificationTaskContract,
  TypeScriptVerificationTaskIndex,
  TypeScriptVerificationTaskKind,
  TypeScriptVerificationTaskRecord,
  TypeScriptVerificationTaskState,
  TypeScriptVerificationWaiver,
} from "./verification.js";
